### ISSUE TITLE
duplicate env values should issue at least a warning

### ISSUE THREAD

**Issue by mdaniel** [replicatedhq/replicated-lint#72]
Currently, the yaml is permitted to have duplicated `env_vars` names, which experientially appears to be last-value-wins. That can be a tricky bug to track down for any reasonably sized `env_vars` block

```yaml
replicated_api_version: 2.11.1
name: example dup env
components:
- containers:
  - image_name: busybox
    env_vars:
    - name: SAMPLE
      value: this is a sample
    - name: SAMPLE
      value: so is this
```

```
$ ./node_modules/.bin/replicated-lint --version
0.8.4
$ ./node_modules/.bin/replicated-lint validate < /app/dup-env.yml
61/61 checks passed.
✓ All clear!
```
